title: "Meet Thakkar"
description: "2nd Year PhD Student at IISc Bangalore | Application of Diffusion Models"
remote_theme: pages-themes/cayman@v0.2.0
url: "https://thakkar-meet.github.io"
baseurl: ""

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Social links
github_username: Thakkar-meet
linkedin_username: meet-thakkar-b720a8201
email: meetjitent@iisc.ac.in

# Include custom header
include:
  - _includes

# Exclude files from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

